### ISSUE TITLE
KeyMasterSideBarList.on_del_group() does not remove group from database

### ISSUE THREAD

**Issue by chmod000** [kebrx/keymaster#3]
Groups don't actually get removed when you press the minus sign because on_del_group() never removes them from the database.

https://github.com/kebrx/keymaster/blob/master/keymaster/groups_listbox.py#L159

**Comment by kebrx** [comment]
On it, apparently I don't think things through when I'm tired.

**Comment by kebrx** [comment]
Fixed!
